### ISSUE TITLE
Reset trials restore all previous data when exporting to Germinate template

### ISSUE THREAD

**Issue by BoMeyering** [cropgeeks/gridscore#27]
### Problem
Sometimes I need to reset a trial to remove collected observations. Normally this works as expected, and reset removes the data points. However, after collecting new data, if you export to Germinate format, Gridscore populates any multivalued traits with previously collected data and any uncollected single traits with the previously collected value.

### What I've done
* Create new trial, collect data, never sync to server
    *  Exports original data as expected
    *  Reset trial and export -> exports a blank trial
    *  Collect new data and export -> exports only new data

* Create a new trial, collect data and sync
    * Exports original data as expected
    * Reset trial, sync, and export -> Pulls in original data from server as expected
    * Reset trial, do not sync, and export -> Still pulls in original data to template (does not export blank trial)
    * Reset trial, collect some data (not all traits), do not sync, and export -> Single Traits: Overwritten with new data, Multi Traits: Includes new data and old data, Single/Mutli traits not recollected after reset are overwritten with previous values.

I realize that this behavior is probably not a bug, so my question is what would be the best way to propagate a reset of values across the trial in the server. For instance, we collect data in the same trial across multiple devices but sometimes we need to reset the trial and collect a new set of values for a different purpose. I want to have a clean slate when exporting to Germinate so it doesn't grab all historical values for a trait, but only what I just recently collected. Are there any solutions to this that don't involve cloning a blank version of the trial?

**Comment by sebastian-raubach** [comment]
Yes, there's an issue with resetting a trial if you're using the GridScore server (that includes the Germinate export) for sharing the data.
While the reset removes all the data for this trial from the local device, it does not remove the data from the server.
If you let me know the ID of the trial by email (the QR code used to share the trial), I can completely remove the trial from the database for you.
We're planning to fix this going forwards, but there are complicated logistics to figure out because of the potentially shared nature of a trial.

**Comment by BoMeyering** [comment]
Thanks, I figured this would not be simple due to the distributed versions of the trial on the server and other devices. For right now, we aren't in any hurry so I can just clone the trial and start fresh. But I'm glad to know that it can be deleted on your end.
